// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentServiceGQL.DataService;

#nullable disable

namespace StudentServiceGQL.Migrations
{
    [DbContext(typeof(StudentServiceContext))]
    partial class StudentServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StudentServiceGQL.DomainObjects.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressID"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateID")
                        .HasColumnType("int");

                    b.Property<string>("StreetOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressID");

                    b.HasIndex("StateID");

                    b.HasIndex("StudentID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressID = 1,
                            City = "Polmero",
                            StateID = 1,
                            StreetOne = "8564 Fresco Street",
                            StreetTwo = "",
                            StudentID = 1,
                            ZipCode = "96542"
                        },
                        new
                        {
                            AddressID = 2,
                            City = "Nina",
                            StateID = 2,
                            StreetOne = "9621 Pinta Lane",
                            StreetTwo = "",
                            StudentID = 2,
                            ZipCode = "52145"
                        });
                });

            modelBuilder.Entity("StudentServiceGQL.DomainObjects.State", b =>
                {
                    b.Property<int>("StateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateID");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateID = 1,
                            Name = "NY"
                        },
                        new
                        {
                            StateID = 2,
                            Name = "CA"
                        });
                });

            modelBuilder.Entity("StudentServiceGQL.DomainObjects.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            AdmissionDate = new DateTime(2020, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 38,
                            DoB = new DateTime(1984, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nicholas",
                            LastName = "Gunn",
                            Program = "Music Studies",
                            StudentNumber = "9580389442"
                        },
                        new
                        {
                            StudentID = 2,
                            AdmissionDate = new DateTime(2021, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Age = 42,
                            DoB = new DateTime(1979, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Charles",
                            LastName = "Freiderick",
                            Program = "Something Something Science",
                            StudentNumber = "9580389442"
                        });
                });

            modelBuilder.Entity("StudentServiceGQL.DomainObjects.Address", b =>
                {
                    b.HasOne("StudentServiceGQL.DomainObjects.State", "State")
                        .WithMany()
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentServiceGQL.DomainObjects.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
